- name: Copy aisloader binary to hosts
  hosts: aisloader_hosts
  become: true
  gather_facts: no

  tasks:
    - name: Copy aisloader binary
      ansible.builtin.copy:
        src: "{{ aisloader_path }}"
        dest: /usr/local/bin/aisloader