---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install deps'
      raw: sudo apt-get update -y && sudo apt-get -y install unzip python git python-simplejson make attr sysstat lsof
  tasks:
    - copy:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0777
      with_items:
        - setupnodes.sh
    - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
      shell: /home/ubuntu/setupnodes.sh >> setupnodes.log
...
