---
- name: Add test tools
  hosts: all
  become: true
  tasks:
    - name: install fio
      apt:
        name: fio
        state: present
        update_cache: yes
    - name: install iperf3
      apt:
        name: iperf3
        state: present
        update_cache: yes
    - name: install nload
      apt:
        name: nload
        state: present
        update_cache: yes
    - name: install iftop
      apt:
        name: iftop
        state: present
        update_cache: yes
    - name: install sysstat
      apt:
        name: sysstat
        state: present
        update_cache: yes
    - name: install lsof
      apt:
        name: lsof
        state: present
        update_cache: yes
    - name: install nodejs
      apt:
        name: nodejs
        state: present
        update_cache: yes
    - name: install nodejs-legacy
      apt:
        name: nodejs-legacy
        state: present
        update_cache: yes
    - name: install collectd
      apt:
        name: collectd
        state: present
        update_cache: yes
    - name: install collectd-utils
      apt:
        name: collectd-utils
        state: present
        update_cache: yes
    - name: Git clone statsd
      shell: cd /opt; git clone https://github.com/etsy/statsd.git


...

