version: '3'
services:
  graphite:
    image: graphiteapp/graphite-statsd
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOBASE=${GOPATH}
    networks:
      - public
      - docker_default
    environment:
      - AIS_NODE_ROLE=proxy
      - AIS_NO_DISK_IO=${AIS_NO_DISK_IO}
      - PORT=${PORT}
      - AIS_PRIMARY_URL=http://${PRIMARY_IP}:${PORT}
      - AIS_BACKEND_PROVIDERS=${AIS_BACKEND_PROVIDERS}
    env_file:
      - /tmp/docker_ais/tmp.env
      - /tmp/docker_ais/aws.env
    user: ${UID:-1000}
    volumes:
      - ${GOPATH}/src:${GOPATH}/src
      - /tmp/ais/${CLUSTER:-0}:/tmp/ais
  target:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOBASE=${GOPATH}
    networks:
      - public
      - docker_default
    environment:
      - AIS_NODE_ROLE=target
      - AIS_NO_DISK_IO=${AIS_NO_DISK_IO}
      - PORT=${PORT}
      - AIS_PRIMARY_URL=http://${PRIMARY_IP}:${PORT}
      - AIS_BACKEND_PROVIDERS=${AIS_BACKEND_PROVIDERS}
    env_file:
      - /tmp/docker_ais/tmp.env
      - /tmp/docker_ais/aws.env
    user: ${UID:-1000}
    volumes:
      - ${GOPATH}/src:${GOPATH}/src
      - /tmp/ais/${CLUSTER:-0}:/tmp/ais
networks:
  docker_default:
    external: true
  public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PUB_SUBNET:-172.5.0.0/24}
