name: lint (on linux)
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, labeled, ready_for_review]
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
      - name: Lint linux
        run: |
          export GOPATH="$(go env GOPATH)"
          make lint
          make fmt-check
          make spell-check
